[workspace]

members = [
    "pyth-sdk",
    "pyth-sdk-solana",
    "pyth-sdk-solana/test-contract",
]

[workspace.dependencies]
pyth-sdk = { path = "./pyth-sdk", version = "0.8.0" }
pyth-sdk-solana = { path = "./pyth-sdk-solana", version = "0.10.4" }

solana-program = ">= 1.10"
borsh = "1.5.7"
borsh-derive = "1.5.7"
serde = "1.0.136"
solana-address = { version = "1.0.0", features = ["atomic", "borsh", "bytemuck", "curve25519", "decode", "dev-context-only-utils", "error", "rand", "serde", "sha2", "std", "syscalls"] }
